/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useState} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  SafeAreaView,
  ScrollView,
} from 'react-native';
import ShowTouches from 'react-native-show-touches-ios';

const App = () => {
  const [buttonWasPressed, setButtonWasPressed] = useState(false);

  return (
    <ShowTouches>
      <SafeAreaView style={styles.container}>
        <TouchableOpacity
          style={styles.button}
          onPress={() => {
            setButtonWasPressed(true);
          }}>
          <Text style={styles.buttonText}>Press Me</Text>
        </TouchableOpacity>
        <Text style={styles.message}>
          {buttonWasPressed ? 'You pressed the button!' : ''}
        </Text>
        <View style={styles.scrollViewContainer}>
          <ScrollView
            style={styles.scrollView}
            showsVerticalScrollIndicator={false}>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
            <Text style={styles.scrollText}>Scroll Me!</Text>
          </ScrollView>
        </View>
      </SafeAreaView>
    </ShowTouches>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'whitesmoke',
  },
  button: {
    backgroundColor: 'royalblue',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  message: {
    margin: 10,
  },
  scrollViewContainer: {
    height: 100,
    margin: 20,
  },
  scrollView: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'white',
  },
  scrollText: {
    fontWeight: '900',
    fontSize: 25,
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

export default App;
